### ISSUE TITLE
系統重新啟動後會無法連線後臺

### ISSUE THREAD

**Issue by lovelivetw** [intranet-panel/intranet#1]
系統重新啟動後會無法連線後臺
目前是將防火牆關閉後問題就解決,有沒有辦法防止被防火牆關閉的問題呢?

很感謝作者大大重新更新了這個面板,資源用的少又齊全時用 很不錯
謝謝

**Comment by doudoudzj** [comment]
Maybe, when the panel is installed, the port settings was not allowed, I will check and solve it. @lovelivetw 
Thank you for your use

**Comment by doudoudzj** [comment]
> Maybe, when the panel is installed, the port settings was not allowed, I will check and solve it. @lovelivetw
> Thank you for your use

This problem has been solved, please reinstall
```shell
wget https://raw.githubusercontent.com/intranet-panel/intranet/master/install.py
python install.py
```
