### ISSUE TITLE
無法自動更新 首頁出現 发生未知错误！

### ISSUE THREAD

**Issue by lovelivetw** [intranet-panel/intranet#2]
第一個問題
系统设置 > 版本升级 沒辦法自動升級>M<
第二個問題
登入後的狀態首頁會出現 "发生未知错误！"

感謝doudoudzj大大 讚嘆doudoudzj大大

**Comment by doudoudzj** [comment]
Update is ready to use
Fixed the checking update error
@lovelivetw
